### ISSUE TITLE
Frontend app plan

### ISSUE THREAD

**Issue by G-Bro** [open-dm/api#16]
I'm prioritising the backend stuff for now, but we can start planning the frontend (and someone can start working on it if they please)

I propose we go with Vue/npm due to familiarity and also because Vue is cool 😎 

And I imagine the client side API for interacting with the server working like so:

````js
Monster.list().then((monsters) ...
Monster.retrieve(id).then((monster) ...
Monster.create(fields).then((monster) ...
Monster.update(id, fields) or monster.update(fields)
````
etc.

**Comment by DanEvans485** [comment]
I want todo this but, would rather have some sort of api down before hand.

**Comment by Newobc** [comment]
I would suggest using blade, and Laravel mix if its feasible, it makes everything so much simpler / less work. Defining routes only once is very refreshing lol..

But as i want to do as little FE as possible, and as much backend as possible (gigiddy), I am not over fussed. 😄
