### ISSUE TITLE
Create Monster

### ISSUE THREAD

**Issue by G-Bro** [open-dm/api#2]
We need an access point to create new monsters

| Request type | URL format | Response |
|--------------|--------------|-----------|
| POST | /api/monsters/create/ | MonsterResource |

Formatting the POST data might be a little nasty

**Comment by G-Bro** [comment]
Monsters created this way should also be associated with the current user #3

**Comment by DanEvans485** [comment]
Do we want to be passing id's back from resources?

**Comment by G-Bro** [comment]
> Do we want to be passing id's back from resources?

I think so because you want to be able to retrieve and update the relations of an object, but I was thinking we could add a code field that was like stripes format of cus_G6hi6KlmA08hj

**Comment by G-Bro** [comment]
(so then we return and retrieve items by that instead, and people can't guess the code of someone else's object)

**Comment by G-Bro** [comment]
I created a demo function for making hash ids before

UGLY CODE WARNING

````php
function generateUniqueId(int $id) {
    $alphabet = 'AaBbCcDdEeFfGgHhJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789';
    $salt = 'isle_of_wight_porcupine';
    $pepper = 'radagast_the_brown';

    $hash = hash('sha256', $salt . $id . $pepper);

    $unique_id = '';
    $remainder = 0;

    for ($i = 0; $i < strlen($hash); $i += 4) {
        $value = hexdec($hash[$i]) + hexdec($hash[$i + 1]) + hexdec($hash[$i + 2]) + hexdec($hash[$i + 3]) + $remainder;

        if ($value > 62) {
            $remainder = $value - 62;
            $value = 62;
        } else {
            $remainder = 0;
        }

        $unique_id .= $alphabet[$value];
    }

    return $unique_id;
}

**Comment by DanEvans485** [comment]
Or [Laravel Encryption](https://laravel.com/docs/5.0/encryption)

**Comment by G-Bro** [comment]
that's like a hundred characters long

**Comment by DanEvans485** [comment]
Never used it. Dunno if you can change the output length. But it should check if you own that item in the db, I was mainly asking if we need them all. Or if we can just update the entire character instead of each piece.

**Comment by G-Bro** [comment]
If you want to give a character a certain weapon, say a greataxe, then i think you could just post the item id for that weapon

**Comment by DanEvans485** [comment]
Ok, I don't have an issue with it. Just wondering if we can reduce unnecessary things.
