### ISSUE TITLE
Monster vs Character

### ISSUE THREAD

**Issue by G-Bro** [open-dm/api#36]
I feel like this is the biggest question mark in how we deal with a Monster vs a Character (who is a monster) where a 'Monster' is essentially a template for characters

To me, there are 2 possible solutions:

1. Leave monster and character separate, which means we have to duplicate all the relations and quite a bit of code. - nasty
2. Make monsters a template character. They exist in the characters table, with an is_template bool set to true - in this case the instance of the monster could have a source_character_id of the original monster record and a character_type of monster (relational)

2 seems like the better solution

**Comment by DanEvans485** [comment]
I do like 2. Avoids the duplicate tables with my I was thinking.

**Comment by DanEvans485** [comment]
If 2 then I will update in my current db seed / refactor branch

**Comment by G-Bro** [comment]
Regarding source character ID I'm just thinking you might want to find all characters that are orcs or all characters that are beholders etc.

**Comment by G-Bro** [comment]
But yes I think let's go with 2

**Comment by DanEvans485** [comment]
I could be wrong but wouldn't an Orc monster have an orc race?

**Comment by G-Bro** [comment]
Yes but so would orc war chief which is a separate Monster type

**Comment by DanEvans485** [comment]
Oooooh Why does it have to be so complicated
